version: 2
log-level: 1
root-markers:
  - ".git"

tools:
  clang-format: &clang-format
    format-command: "clang-format"
    format-stdin: true

  c_formatter_42: &c_formatter_42
    format-command: "/home/musicvivireal/.local/bin/c_formatter_42"
    format-stdin: true

  42_cformat_enhanced: &42_cformat_enhanced
    format-command: "42header ${INPUT}"
    format-stdin: true

  42header:  &42header
    format-command: "42_cformat_enhanced ${INPUT} ${ROOT} --ignore-file .normignore"
    format-stdin: true

languages:
  c:
    - <<: *clang-format 
    - <<: *42_cformat_enhanced
    - <<: *42header
