[".local/share/fonts/apple-color-emoji/AppleColorEmoji.ttf"]
type = "file"
url ="https://github.com/GORAlexComp/AppleColorEmojiFont/raw/58d87f7b5da4625ecc24651630df3b3379f2d3fc/fonts/AppleColorEmoji.ttf" 
exact = true
